// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaL6wZvHS-aTYapgZ7OmhaGCYSijDJ5mE',
    appId: '1:108486831143:web:887b8db738b6a22391f202',
    messagingSenderId: '108486831143',
    projectId: 'flutter-photo-app-373902',
    authDomain: 'flutter-photo-app-373902.firebaseapp.com',
    storageBucket: 'flutter-photo-app-373902.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFLKRSAdzOI9HTAeHNRavTGH8GR8NRKJw',
    appId: '1:108486831143:android:e402beb5475cb14991f202',
    messagingSenderId: '108486831143',
    projectId: 'flutter-photo-app-373902',
    storageBucket: 'flutter-photo-app-373902.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeGLlin6WsL4qSlF90mKq6rNfh9eTkqlo',
    appId: '1:108486831143:ios:89126cc9ea3e04be91f202',
    messagingSenderId: '108486831143',
    projectId: 'flutter-photo-app-373902',
    storageBucket: 'flutter-photo-app-373902.appspot.com',
    androidClientId: '108486831143-chprnl8rcukjhp5o0s4b0l0hvn27dh82.apps.googleusercontent.com',
    iosClientId: '108486831143-tvm13jku14tb20l6ksc82191ubjfts77.apps.googleusercontent.com',
    iosBundleId: 'com.lqd.flutterPhotoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeGLlin6WsL4qSlF90mKq6rNfh9eTkqlo',
    appId: '1:108486831143:ios:89126cc9ea3e04be91f202',
    messagingSenderId: '108486831143',
    projectId: 'flutter-photo-app-373902',
    storageBucket: 'flutter-photo-app-373902.appspot.com',
    androidClientId: '108486831143-chprnl8rcukjhp5o0s4b0l0hvn27dh82.apps.googleusercontent.com',
    iosClientId: '108486831143-tvm13jku14tb20l6ksc82191ubjfts77.apps.googleusercontent.com',
    iosBundleId: 'com.lqd.flutterPhotoApp',
  );
}
